"""Tests for ingest.cleanup: the filtered, levelled copy Whisper reads.

The audio is generated by ffmpeg in a temp directory on every run, as in
test_ingest_resample: no binary fixture is tracked.
"""

from __future__ import annotations

import hashlib
import logging
import subprocess
import wave
from pathlib import Path

import numpy as np
import pytest

from voxtrama.ingest import cleanup
from voxtrama.ingest.cleanup import CLEANED_FILENAME, cleaned_audio


def _quiet_tone(path: Path, sample_rate: int = 44_100, seconds: float = 3.0) -> None:
    """A stereo tone pulsing four times a second, like syllables, at about -48 dBFS.

    A speaker far from the microphone. Much quieter than this (around -65
    dBFS) the noise reduction takes the signal for the noise floor itself.
    """
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi",
         "-i", f"sine=frequency=220:sample_rate={sample_rate}:duration={seconds}",
         "-af", "volume=0.1,tremolo=f=4:d=0.9", "-ac", "2", str(path)],
        check=True,
    )  # fmt: skip


def _read(path: Path) -> tuple[wave._wave_params, np.ndarray]:
    with wave.open(str(path), "rb") as handle:
        params = handle.getparams()
        samples = np.frombuffer(handle.readframes(params.nframes), dtype="<i2")
    return params, samples.astype(np.float64) / 32768.0


def _rms(samples: np.ndarray) -> float:
    return float(np.sqrt(np.mean(np.square(samples))))


def test_the_copy_is_16k_mono_beside_the_recording_and_the_original_is_untouched(
    tmp_path: Path,
) -> None:
    source = tmp_path / "call.wav"
    _quiet_tone(source)
    before = hashlib.sha256(source.read_bytes()).hexdigest()

    cleaned = cleaned_audio(source)

    assert cleaned == tmp_path / CLEANED_FILENAME
    params, _ = _read(cleaned)
    assert (params.framerate, params.nchannels) == (16_000, 1)
    assert hashlib.sha256(source.read_bytes()).hexdigest() == before
    assert not list(tmp_path.glob("*.part"))


def test_a_quiet_recording_comes_out_louder(tmp_path: Path) -> None:
    source = tmp_path / "call.wav"
    _quiet_tone(source)
    _, original = _read(source)

    _, cleaned = _read(cleaned_audio(source))

    assert _rms(cleaned) > 10 * _rms(original)


def test_the_copy_is_made_once(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = tmp_path / "call.wav"
    _quiet_tone(source, seconds=1.0)
    cleaned_audio(source)
    calls: list[Path] = []
    monkeypatch.setattr(cleanup, "clean_for_transcription", lambda src, dst: calls.append(src))

    cleaned_audio(source)

    assert calls == []


def test_a_file_ffmpeg_cannot_read_is_transcribed_as_it_is(
    tmp_path: Path, caplog: pytest.LogCaptureFixture, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A migration test's logging.config.fileConfig (alembic.ini) disables
    # every logger that existed before it: this one, in a full run.
    monkeypatch.setattr(cleanup.logger, "disabled", False)
    source = tmp_path / "call.wav"
    source.write_bytes(b"not audio at all")

    with caplog.at_level(logging.WARNING, logger=cleanup.__name__):
        assert cleaned_audio(source) == source
    assert not (tmp_path / CLEANED_FILENAME).exists()
    assert not list(tmp_path.glob("*.part"))
    assert "without cleaning" in caplog.text
