"""An upload must be an audio or video container, never a playlist.

ffmpeg reads playlists too: an `.m3u8` whose lines name other files. As
measured, an uploaded playlist naming another recording's path made ffmpeg
copy that recording's audio into the new job, which then transcribed it.
The audio is generated by ffmpeg in a temp folder.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from voxtrama.ingest import probe
from voxtrama.ingest.concat import concatenate_parts
from voxtrama.ingest.errors import UnsupportedMediaError
from voxtrama.ingest.probe import probe_media


def _tone(path: Path) -> Path:
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i", "sine=duration=1", str(path)],
        check=True,
    )
    return path


def _playlist_naming(tmp_path: Path, target: Path) -> Path:
    playlist = tmp_path / "p.m3u8"
    playlist.write_text(
        f"#EXTM3U\n#EXT-X-TARGETDURATION:10\n#EXTINF:1.0,\n{target}\n#EXT-X-ENDLIST\n"
    )
    return playlist


def test_an_audio_file_is_accepted(tmp_path: Path) -> None:
    assert probe_media(_tone(tmp_path / "call.wav"))[1] == "wav"


def test_a_playlist_naming_another_file_is_refused(tmp_path: Path) -> None:
    """ffprobe 6 reads it as `hls`; Debian's ffprobe 5 already fails on it. Refused either way."""
    other = _tone(tmp_path / "someone-else.wav")

    with pytest.raises(UnsupportedMediaError):
        probe_media(_playlist_naming(tmp_path, other))


def test_a_container_outside_the_list_is_refused(tmp_path: Path, monkeypatch) -> None:
    report = {"format": {"format_name": "hls", "duration": "1.0"}, "streams": [
        {"codec_type": "audio", "sample_rate": "16000", "channels": 1}
    ]}  # fmt: skip
    monkeypatch.setattr(probe, "_run_ffprobe", lambda source: report)

    with pytest.raises(UnsupportedMediaError, match="not an audio or video file"):
        probe_media(tmp_path / "p.m3u8")


def test_a_playlist_among_the_parts_is_refused_before_joining(tmp_path: Path) -> None:
    other = _tone(tmp_path / "someone-else.wav")
    parts = [_tone(tmp_path / "part1.wav"), _playlist_naming(tmp_path, other)]

    with pytest.raises(UnsupportedMediaError):
        concatenate_parts(parts, tmp_path / "joined.flac")

    assert not (tmp_path / "joined.flac").exists()
