#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_LICENSES.md from requirements.lock.

Every library the Docker image installs is pinned in requirements.lock.
This lists each one with the version the lock pins and the licence its
own package metadata declares, then appends what the lock cannot show:
the programs in the image and the models Voxtrama downloads. Run it after
`make lock`; tests/test_third_party_licenses.py fails until the committed
file matches this output again.
"""

from __future__ import annotations

import re
from importlib import metadata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCK = REPO_ROOT / "requirements.lock"
OUTPUT = REPO_ROOT / "THIRD_PARTY_LICENSES.md"

HEADER = """# Third-party licences

Voxtrama is released under the Apache License 2.0 (see `LICENSE` and
`NOTICE`). It depends on the libraries, programs and models below, which
keep their own licences. This file is generated by
`scripts/generate_third_party_licenses.py` from `requirements.lock`; do not
edit the table by hand.

## Python libraries in the image

| Library | Version | Licence |
|---|---|---|
"""

FOOTER = """
## Programs in the image

- **Python 3.11** (`python:3.11-slim`), PSF-2.0: the base image, with
  Debian's own packages.
- **FFmpeg** (Debian package), GPL-2.0-or-later: a separate program Voxtrama
  runs from the command line, not linked into Voxtrama. Its source is at
  <https://ffmpeg.org> and in Debian's source packages.

## Not distributed with Voxtrama

- **Redis** (`redis:7-alpine`), RSALv2 / SSPLv1: the queue. Docker pulls the
  image from Docker Hub when you start Voxtrama.
- **Ollama and its models**, each under its own licence: installed and
  chosen by you. Voxtrama shows a model's licence before downloading it.

## Models downloaded at first use

- **Whisper** small, medium and large-v3 (faster-whisper conversions), MIT:
  transcription.
- **`speechbrain/spkrec-ecapa-voxceleb`**, Apache-2.0: telling speakers apart.

The model files are never part of the image: they are downloaded into your
data folder the first time a job needs them.
"""


def pinned() -> list[tuple[str, str]]:
    """(name, version) for every `name==version` line of the lock."""
    pairs = re.findall(r"^([A-Za-z0-9_.-]+)==([^\s;\\]+)", LOCK.read_text(), re.MULTILINE)
    return sorted(pairs, key=lambda pair: pair[0].lower())


def licence_of(name: str) -> str:
    """The licence the installed package declares: the SPDX expression first."""
    meta = metadata.metadata(name)
    expression = (meta.get("License-Expression") or "").strip()
    if expression:
        return expression
    classifiers = [
        c.split("::")[-1].strip()
        for c in meta.get_all("Classifier") or []
        if c.startswith("License ::") and c.split("::")[-1].strip() != "OSI Approved"
    ]
    if classifiers:
        return " / ".join(classifiers)
    declared = (meta.get("License") or "").strip()
    return declared if declared and "\n" not in declared and len(declared) <= 60 else "see project"


def render() -> str:
    rows = [f"| {name} | {version} | {licence_of(name)} |" for name, version in pinned()]
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
